spring:
  cloud:
    #/{application}/{profile}[/{label}]
    #/{application}-{profile}.yml #需要配置default-label: master
    #/{label}/{application}-{profile}.yml
    #/{application}-{profile}.properties
    #/{label}/{application}-{profile}.properties
    #如果没有环境（label)则采用default访问
    config:
      server:
        git:
          #github地址
#          uri: https://github.com/carocean/cj-geochat-config-resources.git
          uri: ${docker.spring.cloud.config.server.git.uri:https://gitee.com/carocean/cj-geochat-config-resource.git}
          skipSslValidation: true
          # github账号名
          #username: carocean
          username: ${docker.spring.cloud.config.server.git.username:carocean}
          # github账号密码
          #password: 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
          password: ${docker.spring.cloud.config.server.git.password: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}
          search-paths: ${docker.spring.cloud.config.server.git.search-paths:config}
          timeout: ${docker.spring.cloud.config.server.git.timeout:30}
          default-label: ${docker.spring.cloud.config.server.git.default-label:master}
eureka:
  client:
    register-with-eureka: true  # 是否向注册中心注册自己
    fetchRegistry: true   # 是否从注册中心抓取已有的注册信息，默认true，集群必须设置为true
    service-url:
      # 集群中各个服务注册中心的地址，实际上先一个节点即可，因为服务器集群会复制提供者信息。
      defaultZone: ${docker.geochat.EUREKA_SERVER_URL:http://eureka8761:8761/eureka}
  instance:
    instance-id: cj-geochat-server-config/${server.port}	 # 服务实例Id
    prefer-ip-address: true
    appname: cj-geochat-server-config
    status-page-url: http://localhost:${server.port}${server.servlet.context-path}doc.html